/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "userstatusservice_constants.h"

namespace userstatusservice {

const userstatusserviceConstants g_userstatusservice_constants;

userstatusserviceConstants::userstatusserviceConstants() {
}

} // namespace

