/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef userstatusservice_CONSTANTS_H
#define userstatusservice_CONSTANTS_H

#include "userstatusservice_types.h"

namespace userstatusservice {

class userstatusserviceConstants {
 public:
  userstatusserviceConstants();

};

extern const userstatusserviceConstants g_userstatusservice_constants;

} // namespace

#endif
